/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as PopoutRouteImport } from './routes/popout'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MasterpassRouteImport } from './routes/masterpass'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedNoteidRouteImport } from './routes/shared/$noteid'
import { Route as NotesIdRouteImport } from './routes/notes.$id'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as SharedNoteidKeyRouteImport } from './routes/shared/$noteid/$key'
import { Route as NotesIdAttachmentIdRouteImport } from './routes/notes.$id.$attachmentId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PopoutRoute = PopoutRouteImport.update({
  id: '/popout',
  path: '/popout',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterpassRoute = MasterpassRouteImport.update({
  id: '/masterpass',
  path: '/masterpass',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedNoteidRoute = SharedNoteidRouteImport.update({
  id: '/$noteid',
  path: '/$noteid',
  getParentRoute: () => SharedRoute,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotesRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const SharedNoteidKeyRoute = SharedNoteidKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => SharedNoteidRoute,
} as any)
const NotesIdAttachmentIdRoute = NotesIdAttachmentIdRouteImport.update({
  id: '/$attachmentId',
  path: '/$attachmentId',
  getParentRoute: () => NotesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/extensions': typeof ExtensionsRoute
  '/landing': typeof LandingRoute
  '/masterpass': typeof MasterpassRoute
  '/notes': typeof NotesRouteWithChildren
  '/pitch': typeof PitchRoute
  '/popout': typeof PopoutRoute
  '/reset': typeof ResetRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRouteWithChildren
  '/tags': typeof TagsRoute
  '/verify': typeof VerifyRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/notes/$id': typeof NotesIdRouteWithChildren
  '/shared/$noteid': typeof SharedNoteidRouteWithChildren
  '/notes/$id/$attachmentId': typeof NotesIdAttachmentIdRoute
  '/shared/$noteid/$key': typeof SharedNoteidKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/extensions': typeof ExtensionsRoute
  '/landing': typeof LandingRoute
  '/masterpass': typeof MasterpassRoute
  '/notes': typeof NotesRouteWithChildren
  '/pitch': typeof PitchRoute
  '/popout': typeof PopoutRoute
  '/reset': typeof ResetRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRouteWithChildren
  '/tags': typeof TagsRoute
  '/verify': typeof VerifyRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/notes/$id': typeof NotesIdRouteWithChildren
  '/shared/$noteid': typeof SharedNoteidRouteWithChildren
  '/notes/$id/$attachmentId': typeof NotesIdAttachmentIdRoute
  '/shared/$noteid/$key': typeof SharedNoteidKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/extensions': typeof ExtensionsRoute
  '/landing': typeof LandingRoute
  '/masterpass': typeof MasterpassRoute
  '/notes': typeof NotesRouteWithChildren
  '/pitch': typeof PitchRoute
  '/popout': typeof PopoutRoute
  '/reset': typeof ResetRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRouteWithChildren
  '/tags': typeof TagsRoute
  '/verify': typeof VerifyRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/notes/$id': typeof NotesIdRouteWithChildren
  '/shared/$noteid': typeof SharedNoteidRouteWithChildren
  '/notes/$id/$attachmentId': typeof NotesIdAttachmentIdRoute
  '/shared/$noteid/$key': typeof SharedNoteidKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/extensions'
    | '/landing'
    | '/masterpass'
    | '/notes'
    | '/pitch'
    | '/popout'
    | '/reset'
    | '/settings'
    | '/shared'
    | '/tags'
    | '/verify'
    | '/admin/messages'
    | '/notes/$id'
    | '/shared/$noteid'
    | '/notes/$id/$attachmentId'
    | '/shared/$noteid/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/extensions'
    | '/landing'
    | '/masterpass'
    | '/notes'
    | '/pitch'
    | '/popout'
    | '/reset'
    | '/settings'
    | '/shared'
    | '/tags'
    | '/verify'
    | '/admin/messages'
    | '/notes/$id'
    | '/shared/$noteid'
    | '/notes/$id/$attachmentId'
    | '/shared/$noteid/$key'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/extensions'
    | '/landing'
    | '/masterpass'
    | '/notes'
    | '/pitch'
    | '/popout'
    | '/reset'
    | '/settings'
    | '/shared'
    | '/tags'
    | '/verify'
    | '/admin/messages'
    | '/notes/$id'
    | '/shared/$noteid'
    | '/notes/$id/$attachmentId'
    | '/shared/$noteid/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ExtensionsRoute: typeof ExtensionsRoute
  LandingRoute: typeof LandingRoute
  MasterpassRoute: typeof MasterpassRoute
  NotesRoute: typeof NotesRouteWithChildren
  PitchRoute: typeof PitchRoute
  PopoutRoute: typeof PopoutRoute
  ResetRoute: typeof ResetRoute
  SettingsRoute: typeof SettingsRoute
  SharedRoute: typeof SharedRouteWithChildren
  TagsRoute: typeof TagsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popout': {
      id: '/popout'
      path: '/popout'
      fullPath: '/popout'
      preLoaderRoute: typeof PopoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masterpass': {
      id: '/masterpass'
      path: '/masterpass'
      fullPath: '/masterpass'
      preLoaderRoute: typeof MasterpassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$noteid': {
      id: '/shared/$noteid'
      path: '/$noteid'
      fullPath: '/shared/$noteid'
      preLoaderRoute: typeof SharedNoteidRouteImport
      parentRoute: typeof SharedRoute
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof NotesRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shared/$noteid/$key': {
      id: '/shared/$noteid/$key'
      path: '/$key'
      fullPath: '/shared/$noteid/$key'
      preLoaderRoute: typeof SharedNoteidKeyRouteImport
      parentRoute: typeof SharedNoteidRoute
    }
    '/notes/$id/$attachmentId': {
      id: '/notes/$id/$attachmentId'
      path: '/$attachmentId'
      fullPath: '/notes/$id/$attachmentId'
      preLoaderRoute: typeof NotesIdAttachmentIdRouteImport
      parentRoute: typeof NotesIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMessagesRoute: typeof AdminMessagesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMessagesRoute: AdminMessagesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NotesIdRouteChildren {
  NotesIdAttachmentIdRoute: typeof NotesIdAttachmentIdRoute
}

const NotesIdRouteChildren: NotesIdRouteChildren = {
  NotesIdAttachmentIdRoute: NotesIdAttachmentIdRoute,
}

const NotesIdRouteWithChildren =
  NotesIdRoute._addFileChildren(NotesIdRouteChildren)

interface NotesRouteChildren {
  NotesIdRoute: typeof NotesIdRouteWithChildren
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesIdRoute: NotesIdRouteWithChildren,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface SharedNoteidRouteChildren {
  SharedNoteidKeyRoute: typeof SharedNoteidKeyRoute
}

const SharedNoteidRouteChildren: SharedNoteidRouteChildren = {
  SharedNoteidKeyRoute: SharedNoteidKeyRoute,
}

const SharedNoteidRouteWithChildren = SharedNoteidRoute._addFileChildren(
  SharedNoteidRouteChildren,
)

interface SharedRouteChildren {
  SharedNoteidRoute: typeof SharedNoteidRouteWithChildren
}

const SharedRouteChildren: SharedRouteChildren = {
  SharedNoteidRoute: SharedNoteidRouteWithChildren,
}

const SharedRouteWithChildren =
  SharedRoute._addFileChildren(SharedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ExtensionsRoute: ExtensionsRoute,
  LandingRoute: LandingRoute,
  MasterpassRoute: MasterpassRoute,
  NotesRoute: NotesRouteWithChildren,
  PitchRoute: PitchRoute,
  PopoutRoute: PopoutRoute,
  ResetRoute: ResetRoute,
  SettingsRoute: SettingsRoute,
  SharedRoute: SharedRouteWithChildren,
  TagsRoute: TagsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
